# Generated by Django 5.2 on 2025-04-25 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_book_cover_alter_book_category_alter_order_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
